/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        white: '#FFFFFF',
        fogWhite: '#FCFCFC',
        yellow: {
          DEFAULT: '#FEE500',
          10: '#FFFEF5',
          20: '#FFF9E0',
          30: '#FFF3B3',
          40: '#FFED80',
          70: '#F9D100',
          80: '#D4A900',
        },
        gray: {
          10: '#FAFAFB',
          20: '#f4f4f5',
          30: '#E8E8E9',
          40: '#E0E2E8',
          50: '#BDC1C5',
          60: '#9FA5AD',
          70: '#62686d',
          80: '#454A50',
        },
        black: '#1b1d1f',
        alert: {
          DEFAULT: '#FF4A4A',
          10: '#FFF3F3',
          20: '#FFC1C1',
          30: '#FF9292',
          40: '#FFC1C1',
          50: '#FF5C5C',
        },
        main: '#9F6BFF',
        purple: {
          10: '#F9F5FF',
          20: '#EDE3FF',
          30: '#cfb6ff',
          40: '#bc98ff',
          70: '#8b4dff',
          80: '#4C17AF',
        },
        blue: {
          DEFAULT: '#82A5FF',
          10: '#f4f7ff',
          20: '#E9EBF8',
          30: '#d0ddff',
          40: '#a0baff',
          70: '#4C85FB',
          80: '#001D4A',
        },
        pink: {
          DEFAULT: '#FF83A1',
          10: '#FFF7FB',
          20: '#FFEBF5',
          30: '#FFC3D7',
        },
        secondaryBlue: '#7199FF',
        accentPink: '#FC7B8B',
        hotelYellow: '#FFFCEA',
        kinderGreen: '#F5FEF4',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Poppins', 'sans-serif'],
        pretendard: ['Pretendard', 'sans-serif'],
        jalnan2: ['Jalnan2', 'sans-serif'],
      },
      fontSize : {
        logoText : ['50px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '1000',
          fontFamily: ['Pretendard'],
        }],
        headlineH2B18 : ['18px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '700',
          fontFamily: ['Pretendard'],
        }],
        bodyB3Rg14 : ['14px', {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        bodyB1B18 : ['18px', {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '700',
          fontFamily: ['Pretendard'],
        }],
        bodyB2SemiB16 : ['16px' , {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '600',
          fontFamily: ['Pretendard'],
        }],
        bodyB3SemiB14 : ['14px' , {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '600',
          fontFamily: ['Pretendard'],
        }],
        bodyB2Rg14 : ['14px', {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        bodyB2Rg16 : [ '16px', {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        bodyB2Md16 : ['16px', {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        bodyB2B16 : ['16px', {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '700',
          fontFamily: ['Pretendard'],
        }],
        bodyB3SemiB13 : ['13px', {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '600',
          fontFamily: ['Pretendard'],
        }],
        bodyB3Md14 : ['14px', {
          lineHeight: '140%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        elementRg12 : ['12px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        elementMd12 : ['12px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        elementRg13 : ['13px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        elementMd13 : ['13px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        elementBold13 : ['13px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        elementMd14 : ['14px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        elementBold14 : ['14px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        titleSmBold15 : ['15px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '700',
          fontFamily: ['Pretendard'],
        }],
        titleSmMedium15 : ['15px', {
          lineHeight: '120%',
          letterSpacing: '-0.03em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }], 
        titleMdBold16 : ['16px', {
          lineHeight: '120%',
          letterSpacing: '-0.03em',
          fontWeight: '700',
          fontFamily: ['Pretendard'],
        }],
        txtMiniMedium13 : ['13px', {
          lineHeight: '130%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        titleMiniMedium13 : ['13px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        titleMiniMedium135 : ['14px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        titleSmMedium14 : ['14px', {
          lineHeight: '120%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        titleMdBold18 : ['18px' , {
          lineHeight: '180%',
          letterSpacing: '-0.02em',
          fontWeight: '700',
          fontFamily: ['Pretendard'],
        }],
        textMiniRegular13 : ['13px', {
          lineHeight: '130%',
          letterSpacing: '-0.02em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        textMiniMedium13 : ['13px', {
          lineHeight: '130%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        txtMdInputMedium14 : ['14px', {
          lineHeight: '130%',
          letterSpacing: '-0.02em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
        textMdRegular14 : ['14px', {
          lineHeight: '130%',
          letterSpacing: '-0.02em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        textMdMedium14 : ['14px' , {
          lineHeight: '130%',
          letterSpacing: '-0.02em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        captionSmRegular12 : ['12px', {
          lineHeight: '130%',
          letterSpacing: '-0.03em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        captionSmSB12 : ['12px', {
          lineHeight: '130%',
          letterSpacing: '-0.03em',
          fontWeight: '400',
          fontFamily: ['Pretendard'],
        }],
        lineMedium14 : ['14px', {
          lineHeight: '100%',
          letterSpacing: '-0.03em',
          fontWeight: '500',
          fontFamily: ['Pretendard'],
        }],
      }
    },
  },
  plugins: [
    require('tailwind-scrollbar-hide'),
    // require('@tailwindcss/line-clamp')
  ],
}